services:
  dbservice:
    image: mysql
    container_name: dbservice
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - lms-network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - lms-network

  bookservice:
    build: ./com.lms.books
    container_name: bookservice
    restart: always
    environment:
      MYSQL_HOST: dbservice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      KAFKA_BROKER: kafka
      KAFKA_PORT: 9092
    ports:
      - "9000:9000"
    depends_on:
      dbservice:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - lms-network

  customerservice:
    build: ./com.lms.customer
    container_name: customerservice
    restart: always
    environment:
      MYSQL_HOST: dbservice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      KAFKA_BROKER: kafka
      KAFKA_PORT: 9092
    ports:
      - "9001:9001"
    depends_on:
      dbservice:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - lms-network

  borrowingservice:
    build: ./com.lms.borrowing
    container_name: borrowingservice
    restart: always
    environment:
      MYSQL_HOST: dbservice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      KAFKA_BROKER: kafka
      KAFKA_PORT: 9092
    ports:
      - "9002:9002"
    depends_on:
      dbservice:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge